CodnifyToDo/Controllers/ToDoItemController.cs
using Entities.Models;
using Microsoft.AspNetCore.Mvc;
using Repository.RepositoryInterfaces;
using System;

namespace CodnityToDo.Controllers
{
    public class ToDoItemController : Controller
    {
        private IRepositoryWrapper _repository;
        public ToDoItemController(IRepositoryWrapper repository)
        {
            _repository = repository;
        }
        // GET: ToDoItemController
        public ActionResult Index(string name)
        {
            ViewBag.todos = _repository.ToDoItem.FindByCondition(x => x.UserName == name).ToList();
            return View();
        }

        // GET: ToDoItemController/GetTodos
        public ActionResult GetTodos()
        {
            return View();
        }

        // GET: ToDoItemController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: ToDoItemController/Create
        public ActionResult Create(string name)
        {
            ViewBag.userName = name;
            return View();
        }

        // POST: ToDoItemController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([FromForm] ToDoItem todoItem)
        {
            try
            {
                _repository.ToDoItem.Create(new ToDoItem()
                {
                    Id = Guid.NewGuid(),
                    UserName = todoItem.UserName,
                    Description = todoItem.Description,
                    DeadlineDate = todoItem.DeadlineDate,
                    Created = DateTime.UtcNow,
                    Updated = DateTime.UtcNow,
                    Status  = todoItem.Status
                });
                _repository.Save();
                return RedirectToAction("Index", "Home");
            }
            catch
            {
                return View();
            }
        }

        // GET: ToDoItemController/Edit/--
        public ActionResult Edit(Guid id)
        {
            ViewBag.todoItem = _repository.ToDoItem.FindByCondition(x => x.Id == id).FirstOrDefault();
            return View();
        }

        // POST: ToDoItemController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([FromForm] ToDoItem todoItem)
        {
            try
            {

				_repository.ToDoItem.Update(new ToDoItem
                {
                    Id= todoItem.Id,
                    UserName = todoItem.UserName,
                    Description = todoItem.Description,
                    DeadlineDate = todoItem.DeadlineDate,
                    Created = todoItem.Created,
                    Updated = DateTime.UtcNow,
                    Status = todoItem.Status
                });
                _repository.Save();
                return RedirectToAction("Index", "Home");
            }
            catch
            {
                return View();
            }
        }

        // GET: ToDoItemController/Delete/5
        public ActionResult Delete(Guid id)
        {
            var item = _repository.ToDoItem.FindByCondition(x => x.Id == id).FirstOrDefault();
            if (item != null)
            {
                _repository.ToDoItem.Delete(item);
                _repository.Save();
            }
            return RedirectToAction("Index", "Home");
        }
    }
}

CodnifyToDo/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CodnityToDo</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CodnityToDo.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CodnityToDo</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <partial name="_ToDoListPartial" />
                        
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - CodnityToDo - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

CodnifyToDo/Views/Shared/_ToDoListPartial.cshtml
@using Microsoft.AspNetCore.Identity
@using Entities.Models

@inject SignInManager<User> SignInManager
@inject UserManager<User> UserManager

@*@model List<ToDoItem>*@

@if (SignInManager.IsSignedIn(User))
{
    @if (User.Identity != null)
    {
        <li class="nav-item">
            <a class="nav-link text-dark" asp-area="" asp-controller="ToDoItem" asp-action="Index" asp-route-name="@User.Identity.Name">ToDoItems</a>
        </li>
    }
    
}